### ISSUE TITLE
Manjaro popped up during PINE64 discussion

### ISSUE THREAD

**Issue by darktohka** [arindas/manjarno#12]
This blog post is worth a read (and perhaps inclusion to the readme):

https://blog.brixit.nl/why-i-left-pine64/

**Comment by arindas** [comment]
We could probably include it under the heading "Unfair monopolization of the Pinephone ecosystem". However, I'm not sure if we should. This repository was initially created for desktop users and is not directly related. Furthermore, this is a deeply personal record of the developer, which I am unsure if I should quote without their consent.

I'll close this issue for now. Please feel free to reopen this issue if you find more information or if you want to make a PR related to this issue, summarizing this issue and referencing the link in the README.
