### ISSUE TITLE
The date on https://manjarno.snorlax.sh/ for when Manjaro forgets to renew their SSL certs is wrong

### ISSUE THREAD

**Issue by Terra312** [arindas/manjarno#13]
![image](https://user-images.githubusercontent.com/88807526/185279626-93736b40-003e-4599-ad89-dbba2a967424.png)

on the page it lists the date as 2022-07-17, where it should be 2022-08-17

**Comment by arindas** [comment]
Please file this issue under https://github.com/EmeraldSnorlax/manjarno

@EmeraldSnorlax please take a look.
