### ISSUE TITLE
Meta, minor quibble: the MIT licence mentions software - this is not software, but a document.

### ISSUE THREAD

**Issue by janicez** [arindas/manjarno#18]
Consider text-revising the licence to say "document" rather than "software" and replace "associated documentation" with "associated inserts" (like inserts into a manual), without changing any other terms. I don't believe any of this would impact the legal applicability of the MITL (which I believe is applicable to non-software also), but I'm not a lawyer, so you would need to consult a lawyer before accepting this change.

**Comment by arindas** [comment]
Thank you for bringing this up.

I think this thread might be relevant:
https://opensource.stackexchange.com/questions/6545/is-the-mit-license-suitable-for-documentation

However, you are indeed right in pointing out that we don't explicitly package any software source code. I'll keep this issue open for now.

**Comment by arindas** [comment]
Discussion to be continued on #21
