### ISSUE TITLE
Move to CC0 1.0 License

### ISSUE THREAD

**Issue by arindas** [arindas/manjarno#21]
I feel that the CC0 1.0 License is more aligned with this repository's goals. As it is, we don't package any intellectual property and only collect information from third party resources.

I would like the opinion of all contributors on this repository.

**Comment by EmeraldSnorlax** [comment]
i'm all good with relicensing to CC0 (or any other open source license)

**Comment by arindas** [comment]
On a side note (probably unrelated): This is a fork in the first place. I removed the fork relationship initially since the forks were being taken down aggressively.

However, I beleive it's possible to build up on content licensed by CC0 to MIT License. Will check if the reverse holds true as well.

**Comment by arindas** [comment]
Also on another note: My motivations are probably different from the original owner of this git source tree.

**Comment by arindas** [comment]
@arynor96 @slightlyskepticalpotat @EmeraldSnorlax 

Pinging contributors who have committed to this source tree after the License file was added.

**Comment by arindas** [comment]
The original source tree didn't have a license. That's the complication

**Comment by EmeraldSnorlax** [comment]
in that case, i suppose even keeping MIT is breaking the original source's license? no license means implied copyright rights reserved

**Comment by arindas** [comment]
From GitHub Documentation:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

>>Note: If you publish your source code in a public repository on GitHub, according to the [Terms of Service](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-terms-of-service), other users of GitHub.com have the right to view and fork your repository. If you have already created a repository and no longer want users to have access to the repository, you can make the repository private. When you change the visibility of a repository to private, existing forks or local copies created by other users will still exist. For more information, see "[Setting repository visibility](https://docs.github.com/en/github/administering-a-repository/setting-repository-visibility)."

**Comment by arindas** [comment]
The original repo link: github.com/vizs/manjarno
It was deleted.

**Comment by arindas** [comment]
Please re-open this if anyone wants to pursue this further. I feel we will do fine with MIT license for now.
