### ISSUE TITLE
Switching from Manjaro to Endeavor - Cloning ZSH config, themes, etc

### ISSUE THREAD

**Issue by seantcanavan** [arindas/manjarno#27]
Hey Arindam,

I really wanted to switch to EndeavorOS as well but I found that the default ZSH "magic", for lack of a better term, was too hard to move away from. I absolutely love the zsh experience out of the box for Manjaro and can't switch until I understand it and am able to clone it.

Do you know a way to clone the _entire_ zsh setup from Manjaro to Endeavor? Including defaults, themes, plugins, etc? That's my only blocker right now and the one big thing keeping me on Manjaro.

**Comment by arindas** [comment]
https://github.com/Chrysostomus/manjaro-zsh-config

This repository seems to be zsh config used by Manjaro. See if it contains all the configuration files you need.

**Comment by seantcanavan** [comment]
Woah thank you! And there's already an issue about how that repo works on that repo :smile: 

They have https://github.com/Chrysostomus/manjaro-zsh-config/issues/39 which points to https://gitlab.manjaro.org/packages/community/manjaro-zsh-config/-/blob/master/PKGBUILD

Thanks again! I'll dig into this next time I have a couple of hours free.
