### ISSUE TITLE
AUR Sync

### ISSUE THREAD

**Issue by razzeee** [arindas/manjarno#5]
> So the only way Manjaro can be stable is by literally forking all the Arch related repositories including the AUR and keeping them in sync.

I'm not sure this is technically correct. Can't it be stable if you don't use the AUR, like they ship it? Most people might end up using it, but there are some alternatives, if your after desktop programs.

**Comment by arindas** [comment]
Yes, but the programs might still rely on some specific libraries with the
latest versions.

AppImages or similar formats and static binaries would be alright since
they have no dependencies.

At the end of the day, everything could be solved by building from source
but is it feasible everytime?

**Comment by razzeee** [comment]
Probably not, especially with devices, that are differently powered.

**Comment by MartinX3** [comment]
AppImage, Flatpak and Snap should be fine, since they should deliver the needed libs or depend on other flatpak/snap images delivering these libs.

But AUR would be definitely broken, if the AUR-package author doesn't specify the needed minimal lib dependency from the repo correctly.

**Comment by razzeee** [comment]
Sorry, what I said referenced if building from source would be feasible.

And what you mention is what I hinted at with `alternatives` above.
