### ISSUE TITLE
More accuracy

### ISSUE THREAD

**Issue by mirh** [arindas/manjarno#6]
- If you had to ask me, it's actually more likely for arch to break AUR packages with whatever new update of the day, than manjaro due to their policy of holding back (even because if you compile from source it's far easier for new ABI versions to get in your way, rather than for backwards compatibility with the immediately preceding version getting dropped)
- Even pacman [had](https://security.archlinux.org/advisory) privilege escalation vulnerabilities in the (even closer) past. But of course that alone isn't considered an abysmal security record. Why is that so here instead?
- Pamac isn't the "AUR helper" (even though it can do that too, albeit disabled by default). It's the official package manager, "automatic passwordless updates" are what normal people expect their system to do. 
- Also, what's that specific concern for "casual users" even about? It's not the authentication request that could save gullible ones from getting duped. 
- It wouldn't hurt if that "DDoSing" had some little explanation about what happened. Writing spaghetti code that collapse upon itself on odd days and "not realizing that auto-typing with whatever cheap api is being used becomes burdensome quite quickly" are not the same thing. 
- There was nothing fishy or borderline malicious about finances? You can read [here](https://archived.forum.manjaro.org/t/change-of-treasurer-for-manjaro-community-funds/154888) and [here](https://archived.forum.manjaro.org/t/change-in-manjaro-team-composition/155231) from the horse mouth (bonus point, you have all the lengthy conversations at those links). It was a matter of internal governance and hierarchy, not money or deceit.

**Comment by MartinX3** [comment]
- If you had to ask me, I can confirm, that Arch Linux runs stable on 2 computers and 2 servers.
- Even closer? You list 2 entries from 03-2019 and 10-2019, while the pamac issues happened 04-2021 and 10-2021
- Pamac is an AUR helper. See https://wiki.archlinux.org/title/AUR_helpers#Graphical
- According to the README pamac updates the system without asking for a password. Security aware manjaro users disliked this feature, which got added without any announcement. See https://gitlab.manjaro.org/applications/pamac/-/issues/719 and they reverted this security hole after being criticized about it.
- The mentioned DDoSing has reference links. 
- It was fishy. Why do you have a treasurer, if you kick him anytime he denies something because of rules?
```This was rejected as the policy had not been followed, and I queried the expense. Other privately discussed expenses also came to light.```

**Comment by arindas** [comment]
>Also, what's that specific concern for "casual users" even about? It's not the authentication request that could save gullible ones from getting duped.

At the end of the day, this is a repository that simply states *my reasons* for shifting to a different distro. I don't force my advice on anyone. Casual users are still free to use what they prefer.

**Comment by mirh** [comment]
> while the pamac issues happened 04-2021 and 10-2021

You are thinking of the "DDOS" issues, not the security ones with manjaro-system. 

> The mentioned DDoSing has reference links.

You wouldn't believe the FUD that gets thrown around on websites, after somebody in the comments was told by their cousin that once read a flashy headline, that the issue was about wilful damage, or being envious at them, or some other bullcrap. 
See also the paranoia about the treasurer. 

> It was fishy. Why do you have a treasurer, if you kick him anytime he denies something because of rules?

He wasn't kicked out, he dismissed himself due to the policy divergences. 
The denial wasn't on the specific merit or not of the laptop (indeed, he didn't know much about it and had to further inquiry) but just on the grounds that the proper formal procedure hadn't been followed. 

Then I'm a bit torn on that myself (on one hand shortcutting the rules always looks juvenile/amateurish, on the other it was Phil to do it.. which is pretty close to BDFL afaict), and I'm sad jonathon left, but boy isn't this borderline gossip. 

> Pamac is an AUR helper.

It is **also** *potentially* an AUR helper. 
It's ***not*** out of the box, and the point about unattended or password-authenticated updates is still tangent to that taxonomy. 

> Security aware manjaro users disliked this feature, which got added without any announcement.

Unless the meme of manually inspecting the source code of your updates before ~~applying~~ compiling them applies to you, the dichotomy isn't really between handiness and security, but trust. And I don't use manjaro because I don't trust them is kinda the circular argument, isn't it?

This said of course you can totally dislike automatic updates, and there's nothing wrong with it. 

> At the end of the day, this is a repository that simply states my reasons for shifting to a different distro. I don't force my advice on anyone.

Sure, but indeed I'm failing to see the rationale in many of these reasons. 

SSL certificates expiring? Well, that was years ago, but it's still self-evident and laughable why it's bad. 
Like "one ever" distro-specific issue somehow implying a record of pathetic security? How? (I mean, I'm sure there will have been more issue than just that single one, but in the sense that they aren't having a blatant pattern of carelessness any more special than every other distro, what's the deal?)
Similarly, I could even understand some power user complaining because the updates changed behaviour, but automatic updates are the bread and butter of casual users (in fact, Mint even had problems of lazy users getting stuck to old ass unsupported versions). And it still doesn't relate to installing something (bad) in the first place.
