### ISSUE TITLE
manjaro giving contradictory messages about pamac

### ISSUE THREAD

**Issue by EmeraldSnorlax** [arindas/manjarno#7]
https://github.com/EmeraldSnorlax/manjarno/issues/9#issuecomment-1046608211 and https://github.com/EmeraldSnorlax/manjarno/issues/9#issuecomment-1046636497

**Comment by arindas** [comment]
As pointed out already, pamac and the user's usage is more at fault. Pinning it on Manjaro isn't fair. I'll let this one slide but thank you for the update.
